In [1]:
import numpy as np

In [2]:
list1 = [1, 2, 3]
print("list1:",list1)
print("list1 type:",type(list1))

array1 = np.array(list1)
print("array1:",array1)
print("array1 type:", type(array1))

list1: [1, 2, 3]
list1 type: <class 'list'>
array1: [1 2 3]
array1 type: <class 'numpy.ndarray'>


In [3]:
### shape 형태 확인

array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [4]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


In [5]:
### dtype을 통한 데이터값의 타입

list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)

print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [7]:
### 리스트에는 서로다른 타입을 넣을 수 있지만 array에는 같은 타입만 넣을 수 있다.
### 따라서 서로 다른 타이블 넣게되면 하나의 타입으로 통일된다.

list2 = [1, 2, 'test']   # 문자열로 통일
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]      # 실수로 통일
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [8]:
### astype를 통한 타입 변환

array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')  # int형을 float형으로
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')    # float형을 int형으로
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [10]:
### axis기반의 연산함수 수행

array2 = np.array([[1,2,3],
                  [2,3,4]])

print(array2.sum())        # 행과 열 모두 더함
print(array2.sum(axis=0))  # 행방향으로 계산 
print(array2.sum(axis=1))  # 열방향으로 계산

15
[3 5 7]
[6 9]
